<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQZOf3Px\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQZOf3Px/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQZOf3Px.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQZOf3Px\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQZOf3Px\App_KernelDevDebugContainer([
    'container.build_hash' => 'QZOf3Px',
    'container.build_id' => 'a612592b',
    'container.build_time' => 1599744646,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQZOf3Px');
